### ISSUE TITLE
-t=simple 不會產生 migration file

### ISSUE THREAD

**Issue by kiyayeh** [ventoviro/phoenix#157]
如題，目前需要另外開table 才能夠執行

**Comment by asika32764** [comment]
`-t=simple` 其實是輔助後臺用的簡易前台模板，所以原理上是不會產生 migration file

如果硬是產生 migration file，到時又要再刪掉更麻煩

可以考慮沒有資料表時，單純隱藏錯誤訊息，或者另外提供連基本邏輯都沒有的 `empty` 空模板

**Comment by asika32764** [comment]
研究完成，目前 simple template 是依賴在有資料表下運作的，通常是先從後台產生 migration 後才使用

它會自動建立下面這樣的列表

![p-2016-06-14-003](https://cloud.githubusercontent.com/assets/1639206/16028177/38d24a72-320f-11e6-9911-a8d026b14ffb.jpg)

因為這個過程是自動的，所以沒有資料表一定會報錯，無法隱藏

------------------

這邊要先說明一個觀念，phoenix 的概念還是跟 Rails 與 Laravel 不同的。

Phoenix 產生器建立的是「應用(application)」，不是「鷹架」，這個應用是高度黏合在 phoenix 的 library 下面的。所以不能直接去對比 rails 的 make controller 或 make model

以後要加入單項 class 產生器也是可以，但是目前如果要單純有一個空的 MVC 框框的話，自己用 phpstorm 建立比較快

![p-2016-06-14-004](https://cloud.githubusercontent.com/assets/1639206/16028240/f8dc51aa-320f-11e6-9192-31798bd7d7fd.jpg)

![p-2016-06-14-005](https://cloud.githubusercontent.com/assets/1639206/16028239/f8db5944-320f-11e6-9c7f-ea7c43dcfdbf.jpg)

或是跟上面說的一樣再做一個 `empty` 模板，不過這樣維護成本會越來越高

**Comment by asika32764** [comment]
最後是，這是我說為什麼建議大家碰到問題一定要開 issue，很多開發哲學方面的的、bug 與更新持續追蹤等等的討論，在這邊才能持續運作。

像這次的問題又可以討論需不需要全空的 empty 模板，也才能指派誰來負責完成這件事。不會做我也才能順便教學。一套開發工具要朝什麼方向前進是需要眾人參與討論的。以後有新人有相同疑問也能直接 ref 給他看。

### 參考資訊: PSR 標準的討論過程

https://github.com/php-fig/fig-standards/pull/14
https://github.com/php-fig/fig-standards/pull/755
https://github.com/php-fig/fig-standards/pull/759
https://github.com/php-fig/fig-standards/pull/169

**Comment by asika32764** [comment]
新版改用 `empty` 模板
