### ISSUE TITLE
syntax error on single term pages

### ISSUE THREAD

**Issue by kiyayeh** [ventoviro/phoenix#203]
0. url : 
/www/newww/www/dev.php/front/list/1
1. 除錯
![localhost_www_newww_www_dev_php_front_list_1](https://cloud.githubusercontent.com/assets/5356980/17388931/42107f78-5a32-11e6-9cfa-791d61f4d4d0.jpg)
2. 抓不到
![getcontroller_php_-_newww_-___applications_xampp_xamppfiles_htdocs_www_newww_](https://cloud.githubusercontent.com/assets/5356980/17388934/493cb4e2-5a32-11e6-874b-81f7c6fced75.jpg)

**Comment by asika32764** [comment]
You can not use `List` as a MVC group name since `list` is a PHP reserve keyword.
