### ISSUE TITLE
Phoenix ajax bug

### ISSUE THREAD

**Issue by kiyayeh** [ventoviro/phoenix#327]
### 主旨：
Phoenix ajax bug
### 重現步驟：
use ajax call on IE 11
### 預期結果：
pass
### 實際結果：
![enyi-pc](https://user-images.githubusercontent.com/5356980/27469998-70bee5a8-5824-11e7-9a40-402aa18fec66.jpg)

### 補充
```
typeof url == 'object && url !== null
```

**Comment by asika32764** [comment]
經過測試只有在 url 是 NULL 時才會出現，這本來就是錯誤的使用情境。

你呼叫時的 code 是怎麼樣子?

**Comment by asika32764** [comment]
Fixed in https://github.com/ventoviro/phoenix/commit/cb00c351a6071a4a28e35823dac79e7da8fef2fa
